### ISSUE TITLE
Mailpoet 3 support

### ISSUE THREAD

**Issue by ybonnefond** [seb86/MailPoet-WooCommerce-Add-on#18]
Hi,

This extension can't be installed along with Mailpoet 3 as it is a different plugin front Mailpoet Newsletter.

Is there any plan to support Mailpoet3?

Thanks

**Comment by seb86** [comment]
This extension was commission by the MailPoet team and MailPoet 3 is still in beta at the moment. Once MailPoet 3 has a release candidate I will look into the new API they have developed.

**Comment by ybonnefond** [comment]
Fair enough, I look forward to it!

**Comment by seb86** [comment]
Thank you for creating the issue to remind me.
